
CREATE TABLE CUSTOMER (
    CUST_NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    PHONE_NO VARCHAR2(15),
    CITY VARCHAR2(50) NOT NULL,
    CONSTRAINT CUST_NO_CHECK CHECK (CUST_NO LIKE 'C____')
)


CREATE TABLE ACCOUNT (
    ACCOUNT_NO VARCHAR2(5) PRIMARY KEY,
    TYPE VARCHAR2(2) CHECK (TYPE IN ('SB', 'FD', 'CA')), 
    BALANCE NUMBER CHECK (BALANCE < 10000000),  
    BRANCH_CODE VARCHAR2(5),
    CONSTRAINT FK_ACCOUNT_BRANCH FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH (BRANCH_CODE),
    CONSTRAINT ACCOUNT_NO_CHECK CHECK (ACCOUNT_NO LIKE 'A____') 
);


CREATE TABLE DEPOSITOR (
    CUST_NO VARCHAR2(5),
    ACCOUNT_NO VARCHAR2(5),
    PRIMARY KEY (CUST_NO, ACCOUNT_NO),
    CONSTRAINT FK_DEPOSITOR_CUSTOMER FOREIGN KEY (CUST_NO) REFERENCES CUSTOMER (CUST_NO),
    CONSTRAINT FK_DEPOSITOR_ACCOUNT FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT (ACCOUNT_NO)
);



CREATE TABLE LOAN (
    LOAN_NO VARCHAR2(5) PRIMARY KEY,
    CUST_NO VARCHAR2(5),
    AMOUNT NUMBER CHECK (AMOUNT > 1000),  
    BRANCH_CODE VARCHAR2(5),
    CONSTRAINT FK_LOAN_CUSTOMER FOREIGN KEY (CUST_NO) REFERENCES CUSTOMER (CUST_NO),
    CONSTRAINT FK_LOAN_BRANCH FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH (BRANCH_CODE),
    CONSTRAINT LOAN_NO_CHECK CHECK (LOAN_NO LIKE 'L____') 
);

CREATE TABLE BRANCH (
    BRANCH_CODE VARCHAR2(5) PRIMARY KEY,
    BRANCH_NAME VARCHAR2(100) NOT NULL,
    BRANCH_CITY VARCHAR2(50) CHECK (BRANCH_CITY IN ('DELHI', 'MUMBAI', 'KOLKATA', 'CHENNAI'))
);

CREATE TABLE INSTALLMENT (
    INST_NO NUMBER(2) CHECK (INST_NO<10), 
    LOAN_NO VARCHAR2(5),
    INST_AMOUNT NUMBER NOT NULL,
    CONSTRAINT INSTALLMENT_PK PRIMARY KEY (INST_NO, LOAN_NO),
    CONSTRAINT FK_INSTALLMENT_LOAN FOREIGN KEY (LOAN_NO) REFERENCES LOAN (LOAN_NO)
);
 